apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9091
    isDefault: true
    editable: true

  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: host.docker.internal:5433
    user: postgres
    database: scanner_db
    jsonData:
      database: scanner_db
      sslmode: disable
      postgresVersion: 1800
      timescaledb: false
    secureJsonData:
      password: devpw
    editable: true
